W-8946086
evergage/stream-lib pull request #1
Opened 2021-03-29 22:17 UTC by jacobisaliveandwell

This commit changes the groupId and strips down the pom.xml to
bare essentials for our fork.

A strata config has been added for salesforce CI.

2021-03-29 23:15 UTC, ispringer requested changes

2021-03-29 23:15 UTC, ispringer commented on pom.xml
> +  <groupId>com.evergage</groupId>
new package should be `com.evergage.thirdparty`

2021-03-29 23:20 UTC, jacobisaliveandwell commented on pom.xml
> +  <groupId>com.evergage</groupId>
fixed!

2021-03-29 23:31 UTC, ispringer approved these changes

2021-03-30 04:16 UTC, jacobisaliveandwell commented
@ispringer Do we want to update the version to be `-evg1`, or stick with `astral`? I have to update evergage-product either way.

2021-03-30 11:47 UTC, ispringer commented
> @ispringer Do we want to update the version to be `-evg1`, or stick with `astral`? I have to update evergage-product either way.

Good idea. Let's change it to `evg1` for consistency with all the other forks.

2021-03-30 23:35 UTC, ispringer approved these changes

2021-04-08 17:41 UTC, ispringer approved these changes

2021-04-08 17:42 UTC, merged